apiVersion: batch/v1
kind: Job
metadata:
  name: job-sentinel-createlabel-4-33-3
spec:
  template:
    spec:
      containers:
      - name: pod-sentinel-createlabel-4-33-3
        image: gitlab-registry.nrp-nautilus.io/aomqc/deeplearning_pytorch:bc1aa4e7
        workingDir: /canada/data/set4/batch_33
        command: ["/bin/sh","-c"]
        args:
        - python3 create_label.py --poly CanadaFull_firearea_polygons_set_4.shp
        volumeMounts:
        - name: canada
          mountPath: /canada  
        resources:
            limits:
              memory: 40Gi
              cpu: "2"
              nvidia.com/gpu: 2
            requests:
              memory: 40Gi
              cpu: "2"
              nvidia.com/gpu: 2               
      volumes:
      - name: canada 
        persistentVolumeClaim:
            claimName: canada2019-3
      restartPolicy: OnFailure      
  backoffLimit: 
