apiVersion: batch/v1
kind: Job
metadata:
  name: job-sentinel-pullrepo-1-3-3
spec:
  template:
    spec:
      containers:
      - name: pod-sentinel-pullrepo-1-3-3
        image: alpine/git
        workingDir: /canada/data/set1/batch_3
        args:
          - clone
          - --single-branch
          - https://gitlab.nrp-nautilus.io/aomqc/sentinel_download
          - /canada/data/set1/batch_3        
        volumeMounts:
        - name: canada
          mountPath: /canada
        resources:
            limits:
              memory: 1Gi
              cpu: "1"
            requests:
              memory: 1Gi
              cpu: "1"    
      volumes:
      - name: canada
        persistentVolumeClaim:
            claimName: canada2019-3
      restartPolicy: OnFailure      
  backoffLimit: 