apiVersion: batch/v1
kind: Job
metadata:
  name: job-sentinel-postprocess-5-26-3
spec:
  template:
    spec:
      containers:
      - name: pod-sentinel-postprocess-5-26-3
        image: gitlab-registry.nrp-nautilus.io/aomqc/deeplearning_pytorch:bc1aa4e7
        workingDir: /canada/data/set5/batch_26
        command: ["/bin/sh","-c"]
        args:
        - python3 sentinel_data_postprocessing.py
        volumeMounts:
        - name: canada
          mountPath: /canada  
        resources:
            limits:
              memory: 10Gi
              cpu: "2"
            requests:
              memory: 10Gi
              cpu: "2"               
      volumes:
      - name: canada 
        persistentVolumeClaim:
            claimName: canada2019-3
      restartPolicy: OnFailure      
  backoffLimit: 
